[connections.my_database]
    type="sql"
    dialect="mysql"
    username="root"
    password="15515995"
    host="localhost" # IP or URL
    port=3306 # Port number
    database="ecommerce" # Database name